### ISSUE TITLE
TOC not being generated properly for pandas-gbq

### ISSUE THREAD

**Issue by dandhlee** [googleapis/sphinx-docfx-yaml#269]
I've noticed that with the recent updates the TOC looks deformed.

Previously: 

```
- items:
  - href: privacy.md
    name: Privacy
  - href: contributing.md
    name: Contributing to pandas-gbq
  - href: changelog.md
    name: Changelog
  - href: writing.md
    name: Writing Tables
  - href: intro.md
    name: Introduction
  - href: api.md
    name: API Reference
  - href: install.md
    name: Installation
  - href: reading.md
    name: Reading Tables
  - items:
    - name: Context
      uid: pandas_gbq.Context
    name: Context
  name: pandas-gbq
```

with newest sphinx plugin version:
```
- items:
  - - items:
      - name: Context
        uid: pandas_gbq.Context
      name: Context
  name: pandas-gbq
```
Seems like missing the index pages is indeed a problem. :/
